"""Repo-wide hygiene checks on SKILL.md sources.

WHY THIS EXISTS. Several skills under ``skills/`` and ``optional-skills/`` are
generated by an upstream documentation scraper (they carry the marker string
``automatically generated from official documentation`` and tell you to
"Re-run the scraper" to refresh). That scraper is NOT in this repository, so it
cannot be fixed here — but its output lands here, and its "Quick Reference /
Common Patterns" extractor has failed in BOTH directions:

* ``pytorch-fsdp`` got eight WHOLE documentation pages inlined as pattern text.
  SKILL.md reached 160,326 bytes on 130 lines, one line being 130,541 chars.
  That matters because ``tools/skills_tool.py`` ``skill_view()`` reads SKILL.md
  with no truncation and ``agent/skill_commands.py`` injects it on activation —
  roughly 40k tokens of context per trigger. Fixed in b42748df2f.
* ``unsloth`` got ZERO patterns and kept the scraper's unfilled placeholder,
  and separately listed only one of its three reference files, hiding 1.1MB.
  Fixed in 6a78585a4f / 565220c919.

These tests are the repo-side guard: they fail when either failure mode arrives
again, whether from a scraper re-run or a hand edit.

NOTE ON THRESHOLDS. ``MAX_LINE`` is deliberately about LINE length, not file
size. Size does not discriminate: ``research-paper-writing`` is 106,051 bytes
and perfectly healthy at 2,377 lines with a 334-char longest line, while the
broken pytorch-fsdp was 130 lines with a 130,541-char one.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
SKILL_ROOTS = (REPO_ROOT / "skills", REPO_ROOT / "optional-skills")

# Longest line seen in a healthy SKILL.md is ~850 chars (creative/humanizer).
# 20,000 leaves multiple orders of headroom while still catching a whole
# documentation page pasted onto one line.
MAX_LINE = 20_000

# The scraper's placeholder, left when its pattern extractor returns nothing.
PLACEHOLDER = "Quick reference patterns will be added as you use the skill"

SCRAPER_MARKER = "automatically generated from official documentation"


def _skill_files() -> list[Path]:
    out: list[Path] = []
    for root in SKILL_ROOTS:
        if root.is_dir():
            out.extend(sorted(root.rglob("SKILL.md")))
    return out


def _read(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def _rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


@pytest.fixture(scope="module")
def skill_files() -> list[Path]:
    files = _skill_files()
    # Guard the guard: if the globs stop matching, every test below would pass
    # vacuously and this file would silently stop protecting anything.
    assert len(files) > 100, "expected >100 SKILL.md files, found %d" % len(files)
    return files


def test_no_skill_md_has_a_runaway_line(skill_files):
    """A whole documentation page pasted onto one line is the pytorch-fsdp bug."""
    offenders = []
    for path in skill_files:
        longest = max((len(line) for line in _read(path).split("\n")), default=0)
        if longest > MAX_LINE:
            offenders.append("%s (longest line %d chars)" % (_rel(path), longest))
    assert not offenders, (
        "SKILL.md is injected into agent context in full, so a runaway line costs "
        "context on every activation. Move the bulk into references/ and keep a "
        "short Quick Reference:\n  " + "\n  ".join(offenders)
    )


def test_no_skill_md_keeps_the_scraper_placeholder(skill_files):
    """An unfilled Quick Reference is the unsloth bug: zero patterns extracted."""
    offenders = [_rel(p) for p in skill_files if PLACEHOLDER in _read(p)]
    assert not offenders, (
        "The scraper's pattern extractor produced nothing and left its placeholder. "
        "Fill the section with patterns copied from the skill's own references/:\n  "
        + "\n  ".join(offenders)
    )


def test_scraper_skills_list_every_reference_file(skill_files):
    """Every file in references/ must be reachable from SKILL.md and index.md.

    Restricted to scraper-generated skills, which are the ones using this exact
    bullet format. Hand-written skills reference their files as prose or links,
    and including them here produced 77 false positives.
    """
    offenders = []
    for path in skill_files:
        text = _read(path)
        refs_dir = path.parent / "references"
        index = refs_dir / "index.md"
        if SCRAPER_MARKER not in text or not index.exists():
            continue
        on_disk = {p.name for p in refs_dir.glob("*.md")} - {"index.md"}
        in_skill = set(re.findall(r"(?m)^- \*\*([^*]+\.md)\*\*", text))
        in_index = set(re.findall(r"\*\*File:\*\* `([^`]+)`", _read(index)))
        missing = (on_disk - in_skill) | (on_disk - in_index)
        if missing:
            offenders.append("%s: %s not listed" % (_rel(path), sorted(missing)))
    assert not offenders, (
        "reference files exist on disk but are unreachable from the skill:\n  "
        + "\n  ".join(offenders)
    )


def test_scraper_skills_are_still_detectable(skill_files):
    """The marker the two tests above key on must still match something.

    If the upstream scraper changes its boilerplate, those tests would quietly
    check nothing. This fails loudly instead so the marker gets updated.
    """
    scraped = [_rel(p) for p in skill_files if SCRAPER_MARKER in _read(p)]
    assert scraped, (
        "no SKILL.md carries %r any more — the scraper's boilerplate probably "
        "changed, so update SCRAPER_MARKER (and PLACEHOLDER) or these tests are "
        "vacuous" % SCRAPER_MARKER
    )
